config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "top#index"
  resources :quizzes do
    collection do
      get "responce"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quiz.rb
class Quiz < ApplicationRecord
  with_options presence: true do
    validates :question
    validates :answer
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :authenticate_user!, except: [:responce]
  before_action :set_quiz, only: [:edit, :update, :destroy]

  def index
    @quizzes = Quiz.order(created_at: :desc)
  end

  def new
    @quiz = Quiz.new
  end

  def create
    @quiz = Quiz.create(quiz_params)
    if @quiz.save
      redirect_to new_quiz_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @quiz.update(quiz_params)
      redirect_to quizzes_path
    else
      render :edit
    end
  end

  def destroy
    if @quiz.destroy
      redirect_to quizzes_path
    else
      render :edit
    end
  end

  def responce
    @quiz = Quiz.order('RAND()').limit(1)
  end

  private

  def quiz_params
    params.require(:quiz).permit(:question, :answer, :remark)
  end

  def set_quiz
    @quiz = Quiz.find(params[:id])
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/_quiz.html.erb
<div><%= form.text_area :question, placeholder: "問題" , rows: "3"%></div>
<div><%= form.text_area :answer, placeholder: "答え" , rows: "3"%></div>
<div><%= form.text_area :remark, placeholder: "備考", rows: "6" %></div>

app/views/quizzes/edit.html.erb
<div class="create-row">
  <div class="quiz-create">
  <h3>クイズ編集ページ</h3>
    <%= form_with model: @quiz, local: true do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>
      <%= render partial: "quiz", locals: { form: form } %>
      <%= form.submit "変更" %>
    <% end %>
  </div>
  <div><%= link_to "戻る", quizzes_path %></div>
</div>

app/views/quizzes/index.html.erb
<h2>クイズ一覧</h2>
<%= link_to "戻る",root_path %>
<div class= quiz-list>

  <% if @quizzes.present?%>

    <% @quizzes.each do |quiz| %>
      <div><%= quiz.question %></div>
      <%= link_to "編集", edit_quiz_path(quiz.id) %>
      <%= link_to "削除", quiz , method: :delete %>

    <%end%>
  <% else %>
    <div>登録されているクイズはありません</div>
  <% end %>

</div>

app/views/quizzes/new.html.erb
<div class="create-row">
  <div class="quiz-create">
    <h3>クイズ作成ページ</h3>
    <%= form_with model: @quiz, local: true do |form| %>
    <%= render 'layouts/error_messages', model: form.object %>
    <%= render partial: "quiz", locals: { form: form } %>
      <%= form.submit "追加" %>
    <% end %>
  </div>
  <div><%= link_to "戻る", root_path %></div>
</div>

app/views/quizzes/responce.html.erb
<div class="r-home">
  <div class="r-title">次の問題に答えてください</div>

  <div class=r-menu>
    <%= link_to "終了", root_path ,:style=>"text-decoration: none;"%>
    <div class=r-right>
    <%= link_to "次へ", responce_quizzes_path,:style=>"text-decoration: none;" %>
    </div>
  </div>

  <% @quiz.each do |quiz| %>
    <div class="r-question">Q.<%=quiz.question %></div>
    <%#入力蘭%>
    <div class="answer-form"><textarea></textarea></div>
    <%#ボタンを押すと表示%>
    <div class = "correct hidden" id = correct-look>
      <div class=correct-look>答え</div>
      <%= quiz.answer %>
      <div class=correct-look>備考</div>
      <%= quiz.remark %>
    </div>
  <%end%>
  <button class=look id="answer-look">答えを見る</button>
  
</div>

app/views/top/index.html.erb
<% if user_signed_in? %>
<%= link_to "クイズリスト", quizzes_path %>
<%= link_to "クイズ追加", new_quiz_path %>
<%= link_to "ログアウト",  destroy_user_session_path, method: :delete %>
<%= link_to "管理情報編集",  edit_user_registration_path %>
<% else %>
<div><%= link_to "管理者ページ", new_user_session_path %></div>
<% end %>

<div class="top">
  <div class="title">プログラミング学習クイズ
  </div>
  <div class="start">
  <%= link_to "クイズスタート",responce_quizzes_path,:style=>"text-decoration: none;" %>
  </div>
</div>